name: postman-pull-request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        id: step_1
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      # Make directory to upload the test results
      - name: Make Directory for results
        id: step_2
        run: mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        id: step_3
        run: |
          newman run restful-booker.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        id: step_4
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults

      - name: Slack Notification
        uses : act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: All_test 10, Saccess 8, Falied 1, Skiped 1
                   Newman Dashboard
          channel: '#aqa-notification'
        if: always()
